[Interface]
#ServidorVPN
Address = 10.0.0.1/32               #IP en la red
PrivateKey = <Clave_Privada>        #Clave privada
ListenPort = 51820                  #Puerto Salida

#Cliente
[Peer]
PublicKey = <ClavePublica>          #ClavePublica
AllowedIPs = 10.0.0.2/32            #Ip permitida en la conexion



# Las claves privadas y publicas se crearán con
# sudo wg genkey|tee private.key | wg pubkey>public.key